version: '3.7'

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      #local dir/files: docker dir/files
      - $HOME/uzrnem/db/mysql_db:/var/lib/mysql
      - $HOME/uzrnem/db/mysql_db_files:/sql_files
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mysqladmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1 // IF HOST is required, in case of local mysql and docker php myadmin
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8000:80"
    networks:
      - app-tier

  expense:
    depends_on:
      - db
    image: expense:1.0.0
    container_name: expenses
    environment:
      EXP_CONFIG_DATABASE_NAME: expense
      EXP_CONFIG_USER_NAME: root
      EXP_CONFIG_PASS_NAME: root
      EXP_CONFIG_HOST_NAME: db
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - app-tier

volumes:
  db_data: {}
